package com.reddit.type;

import fg3.ux;
import fm3.a;
import kotlin.Metadata;
import kotlin.collections.c0;
import l9.e0;
import org.jetbrains.annotations.NotNull;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: r8-map-id-e80f24f96f1ccf116f81bc3e46b51cedd71acc29abd4f2606e8114f6ad393ac2 */
@Metadata(d1 = {"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0010\u000e\n\u0002\bs\b\u0086\u0081\u0002\u0018\u0000 \t2\b\u0012\u0004\u0012\u00020\u00000\u0001:\u0001\nB\u0011\b\u0002\u0012\u0006\u0010\u0003\u001a\u00020\u0002¢\u0006\u0004\b\u0004\u0010\u0005R\u0017\u0010\u0003\u001a\u00020\u00028\u0006¢\u0006\f\n\u0004\b\u0003\u0010\u0006\u001a\u0004\b\u0007\u0010\bj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bEj\u0002\bFj\u0002\bGj\u0002\bHj\u0002\bIj\u0002\bJj\u0002\bKj\u0002\bLj\u0002\bMj\u0002\bNj\u0002\bOj\u0002\bPj\u0002\bQj\u0002\bRj\u0002\bSj\u0002\bTj\u0002\bUj\u0002\bVj\u0002\bWj\u0002\bXj\u0002\bYj\u0002\bZj\u0002\b[j\u0002\b\\j\u0002\b]j\u0002\b^j\u0002\b_j\u0002\b`j\u0002\baj\u0002\bbj\u0002\bcj\u0002\bdj\u0002\bej\u0002\bfj\u0002\bgj\u0002\bhj\u0002\bij\u0002\bjj\u0002\bkj\u0002\blj\u0002\bmj\u0002\bnj\u0002\boj\u0002\bpj\u0002\bqj\u0002\brj\u0002\bsj\u0002\bt¨\u0006u"}, d2 = {"Lcom/reddit/type/ModActionType;", "", "", "rawValue", "<init>", "(Ljava/lang/String;ILjava/lang/String;)V", "Ljava/lang/String;", "getRawValue", "()Ljava/lang/String;", "Companion", "fg3/ux", "ACCEPT_MODERATOR_INVITE", "ADD_COMMUNITY_TOPICS", "ADD_CONTRIBUTOR", "ADD_ENFORCEMENT_ACTION_FEEDBACK", "ADD_MODERATOR", "ADD_NOTE", "ADD_REMOVAL_REASON", "ADJUST_POST_CROWD_CONTROL_LEVEL", "ENABLE_POST_CROWD_CONTROL_FILTER", "DISABLE_POST_CROWD_CONTROL_FILTER", "APPROVE_AWARD", "APPROVE_COMMENT", "APPROVE_LINK", "BAN_USER", "CREATE_AWARD", "CREATE_SCHEDULED_POST", "CREATE_REMOVAL_REASON", "COLLECTIONS", "COMMUNITY_STATUS", "COMMUNITY_STYLING", "COMMUNITY_WELCOME_PAGE", "COMMUNITY_WIDGETS", "CREATE_RULE", "DELETE_AWARD", "DELETE_RULE", "DELETE_SCHEDULED_POST", "DEV_PLATFORM_APP_CHANGED", "DEV_PLATFORM_APP_DISABLED", "DEV_PLATFORM_APP_ENABLED", "DEV_PLATFORM_APP_INSTALLED", "DEV_PLATFORM_APP_UNINSTALLED", "DELETE_OVERRIDDEN_CLASSIFICATION", "DELETE_NOTE", "DELETE_REMOVAL_REASON", "DISABLE_AWARD", "DISTINGUISH", "EDIT_COMMENT_REQUIREMENTS", "EDIT_ENFORCEMENT_ACTION", "EDIT_FLAIR", "EDIT_POST_REQUIREMENTS", "EDIT_RULE", "EDIT_SAVED_RESPONSE", "EDIT_SCHEDULED_POST", "EDIT_SETTINGS", "ENABLE_AWARD", "EVENTS", "HIDDEN_AWARD", "IGNORE_REPORTS", "INVITE_MODERATOR", "INVITE_SUBSCRIBER", "LOCK", "MARK_NSFW", "MARK_ORIGINAL_CONTENT", "MOD_AWARD_GIVEN", "MODMAIL_ENROLLMENT", "MUTE_USER", "OVERRIDE_CLASSIFICATION", "REMOVE_COMMENT", "REMOVE_COMMUNITY_TOPICS", "REMOVE_CONTRIBUTOR", "REMOVE_LINK", "REMOVE_MODERATOR", "REMOVE_WIKI_CONTRIBUTOR", "REORDER_MODERATORS", "REORDER_REMOVAL_REASON", "REORDER_RULES", "REQUEST_ASSISTANCE", "SET_CONTEST_MODE", "SET_PERMISSIONS", "SET_SUGGESTEDSORT", "SHOW_COMMENT", "SNOOZE_REPORTS", "SPAM_COMMENT", "SPAM_LINK", "SPOILER", "STICKY", "SUBMIT_CONTENT_RATING_SURVEY", "SUBMIT_SCHEDULED_POST", "UNBAN_USER", "UNIGNORE_REPORTS", "UNINVITE_MODERATOR", "UNLOCK", "UNMUTE_USER", "UNSET_CONTEST_MODE", "UNSNOOZE_REPORTS", "UNSPOILER", "UNSTICKY", "UPDATE_REMOVAL_REASON", "WIKI_BANNED", "WIKI_CONTRIBUTOR", "WIKI_PAGE_LISTED", "WIKI_PERM_LEVEL", "WIKI_REVISE", "WIKI_UNBANNED", "CHAT_APPROVE_MESSAGE", "CHAT_REMOVE_MESSAGE", "CHAT_BAN_USER", "CHAT_UNBAN_USER", "CHAT_INVITE_HOST", "CHAT_REMOVE_HOST", "MOD_RECRUITMENT_ENABLE", "MOD_RECRUITMENT_DISABLE", "MOD_RECRUITMENT_UPDATE_TEMPLATE", "MOD_RECRUITMENT_APPLICATION_RESPOND", "MOD_RECRUITMENT_APPLICATION_REMOVE", "UNKNOWN__", "graphql"}, k = 1, mv = {2, 3, 0}, xi = 50)
/* loaded from: classes3.dex */
public final class ModActionType {
    private static final /* synthetic */ a $ENTRIES;
    private static final /* synthetic */ ModActionType[] $VALUES;

    @NotNull
    public static final ux Companion;

    @NotNull
    private static final e0 type;

    @NotNull
    private final String rawValue;
    public static final ModActionType ACCEPT_MODERATOR_INVITE = new ModActionType("ACCEPT_MODERATOR_INVITE", 0, "ACCEPT_MODERATOR_INVITE");
    public static final ModActionType ADD_COMMUNITY_TOPICS = new ModActionType("ADD_COMMUNITY_TOPICS", 1, "ADD_COMMUNITY_TOPICS");
    public static final ModActionType ADD_CONTRIBUTOR = new ModActionType("ADD_CONTRIBUTOR", 2, "ADD_CONTRIBUTOR");
    public static final ModActionType ADD_ENFORCEMENT_ACTION_FEEDBACK = new ModActionType("ADD_ENFORCEMENT_ACTION_FEEDBACK", 3, "ADD_ENFORCEMENT_ACTION_FEEDBACK");
    public static final ModActionType ADD_MODERATOR = new ModActionType("ADD_MODERATOR", 4, "ADD_MODERATOR");
    public static final ModActionType ADD_NOTE = new ModActionType("ADD_NOTE", 5, "ADD_NOTE");
    public static final ModActionType ADD_REMOVAL_REASON = new ModActionType("ADD_REMOVAL_REASON", 6, "ADD_REMOVAL_REASON");
    public static final ModActionType ADJUST_POST_CROWD_CONTROL_LEVEL = new ModActionType("ADJUST_POST_CROWD_CONTROL_LEVEL", 7, "ADJUST_POST_CROWD_CONTROL_LEVEL");
    public static final ModActionType ENABLE_POST_CROWD_CONTROL_FILTER = new ModActionType("ENABLE_POST_CROWD_CONTROL_FILTER", 8, "ENABLE_POST_CROWD_CONTROL_FILTER");
    public static final ModActionType DISABLE_POST_CROWD_CONTROL_FILTER = new ModActionType("DISABLE_POST_CROWD_CONTROL_FILTER", 9, "DISABLE_POST_CROWD_CONTROL_FILTER");
    public static final ModActionType APPROVE_AWARD = new ModActionType("APPROVE_AWARD", 10, "APPROVE_AWARD");
    public static final ModActionType APPROVE_COMMENT = new ModActionType("APPROVE_COMMENT", 11, "APPROVE_COMMENT");
    public static final ModActionType APPROVE_LINK = new ModActionType("APPROVE_LINK", 12, "APPROVE_LINK");
    public static final ModActionType BAN_USER = new ModActionType("BAN_USER", 13, "BAN_USER");
    public static final ModActionType CREATE_AWARD = new ModActionType("CREATE_AWARD", 14, "CREATE_AWARD");
    public static final ModActionType CREATE_SCHEDULED_POST = new ModActionType("CREATE_SCHEDULED_POST", 15, "CREATE_SCHEDULED_POST");
    public static final ModActionType CREATE_REMOVAL_REASON = new ModActionType("CREATE_REMOVAL_REASON", 16, "CREATE_REMOVAL_REASON");
    public static final ModActionType COLLECTIONS = new ModActionType("COLLECTIONS", 17, "COLLECTIONS");
    public static final ModActionType COMMUNITY_STATUS = new ModActionType("COMMUNITY_STATUS", 18, "COMMUNITY_STATUS");
    public static final ModActionType COMMUNITY_STYLING = new ModActionType("COMMUNITY_STYLING", 19, "COMMUNITY_STYLING");
    public static final ModActionType COMMUNITY_WELCOME_PAGE = new ModActionType("COMMUNITY_WELCOME_PAGE", 20, "COMMUNITY_WELCOME_PAGE");
    public static final ModActionType COMMUNITY_WIDGETS = new ModActionType("COMMUNITY_WIDGETS", 21, "COMMUNITY_WIDGETS");
    public static final ModActionType CREATE_RULE = new ModActionType("CREATE_RULE", 22, "CREATE_RULE");
    public static final ModActionType DELETE_AWARD = new ModActionType("DELETE_AWARD", 23, "DELETE_AWARD");
    public static final ModActionType DELETE_RULE = new ModActionType("DELETE_RULE", 24, "DELETE_RULE");
    public static final ModActionType DELETE_SCHEDULED_POST = new ModActionType("DELETE_SCHEDULED_POST", 25, "DELETE_SCHEDULED_POST");
    public static final ModActionType DEV_PLATFORM_APP_CHANGED = new ModActionType("DEV_PLATFORM_APP_CHANGED", 26, "DEV_PLATFORM_APP_CHANGED");
    public static final ModActionType DEV_PLATFORM_APP_DISABLED = new ModActionType("DEV_PLATFORM_APP_DISABLED", 27, "DEV_PLATFORM_APP_DISABLED");
    public static final ModActionType DEV_PLATFORM_APP_ENABLED = new ModActionType("DEV_PLATFORM_APP_ENABLED", 28, "DEV_PLATFORM_APP_ENABLED");
    public static final ModActionType DEV_PLATFORM_APP_INSTALLED = new ModActionType("DEV_PLATFORM_APP_INSTALLED", 29, "DEV_PLATFORM_APP_INSTALLED");
    public static final ModActionType DEV_PLATFORM_APP_UNINSTALLED = new ModActionType("DEV_PLATFORM_APP_UNINSTALLED", 30, "DEV_PLATFORM_APP_UNINSTALLED");
    public static final ModActionType DELETE_OVERRIDDEN_CLASSIFICATION = new ModActionType("DELETE_OVERRIDDEN_CLASSIFICATION", 31, "DELETE_OVERRIDDEN_CLASSIFICATION");
    public static final ModActionType DELETE_NOTE = new ModActionType("DELETE_NOTE", 32, "DELETE_NOTE");
    public static final ModActionType DELETE_REMOVAL_REASON = new ModActionType("DELETE_REMOVAL_REASON", 33, "DELETE_REMOVAL_REASON");
    public static final ModActionType DISABLE_AWARD = new ModActionType("DISABLE_AWARD", 34, "DISABLE_AWARD");
    public static final ModActionType DISTINGUISH = new ModActionType("DISTINGUISH", 35, "DISTINGUISH");
    public static final ModActionType EDIT_COMMENT_REQUIREMENTS = new ModActionType("EDIT_COMMENT_REQUIREMENTS", 36, "EDIT_COMMENT_REQUIREMENTS");
    public static final ModActionType EDIT_ENFORCEMENT_ACTION = new ModActionType("EDIT_ENFORCEMENT_ACTION", 37, "EDIT_ENFORCEMENT_ACTION");
    public static final ModActionType EDIT_FLAIR = new ModActionType("EDIT_FLAIR", 38, "EDIT_FLAIR");
    public static final ModActionType EDIT_POST_REQUIREMENTS = new ModActionType("EDIT_POST_REQUIREMENTS", 39, "EDIT_POST_REQUIREMENTS");
    public static final ModActionType EDIT_RULE = new ModActionType("EDIT_RULE", 40, "EDIT_RULE");
    public static final ModActionType EDIT_SAVED_RESPONSE = new ModActionType("EDIT_SAVED_RESPONSE", 41, "EDIT_SAVED_RESPONSE");
    public static final ModActionType EDIT_SCHEDULED_POST = new ModActionType("EDIT_SCHEDULED_POST", 42, "EDIT_SCHEDULED_POST");
    public static final ModActionType EDIT_SETTINGS = new ModActionType("EDIT_SETTINGS", 43, "EDIT_SETTINGS");
    public static final ModActionType ENABLE_AWARD = new ModActionType("ENABLE_AWARD", 44, "ENABLE_AWARD");
    public static final ModActionType EVENTS = new ModActionType("EVENTS", 45, "EVENTS");
    public static final ModActionType HIDDEN_AWARD = new ModActionType("HIDDEN_AWARD", 46, "HIDDEN_AWARD");
    public static final ModActionType IGNORE_REPORTS = new ModActionType("IGNORE_REPORTS", 47, "IGNORE_REPORTS");
    public static final ModActionType INVITE_MODERATOR = new ModActionType("INVITE_MODERATOR", 48, "INVITE_MODERATOR");
    public static final ModActionType INVITE_SUBSCRIBER = new ModActionType("INVITE_SUBSCRIBER", 49, "INVITE_SUBSCRIBER");
    public static final ModActionType LOCK = new ModActionType("LOCK", 50, "LOCK");
    public static final ModActionType MARK_NSFW = new ModActionType("MARK_NSFW", 51, "MARK_NSFW");
    public static final ModActionType MARK_ORIGINAL_CONTENT = new ModActionType("MARK_ORIGINAL_CONTENT", 52, "MARK_ORIGINAL_CONTENT");
    public static final ModActionType MOD_AWARD_GIVEN = new ModActionType("MOD_AWARD_GIVEN", 53, "MOD_AWARD_GIVEN");
    public static final ModActionType MODMAIL_ENROLLMENT = new ModActionType("MODMAIL_ENROLLMENT", 54, "MODMAIL_ENROLLMENT");
    public static final ModActionType MUTE_USER = new ModActionType("MUTE_USER", 55, "MUTE_USER");
    public static final ModActionType OVERRIDE_CLASSIFICATION = new ModActionType("OVERRIDE_CLASSIFICATION", 56, "OVERRIDE_CLASSIFICATION");
    public static final ModActionType REMOVE_COMMENT = new ModActionType("REMOVE_COMMENT", 57, "REMOVE_COMMENT");
    public static final ModActionType REMOVE_COMMUNITY_TOPICS = new ModActionType("REMOVE_COMMUNITY_TOPICS", 58, "REMOVE_COMMUNITY_TOPICS");
    public static final ModActionType REMOVE_CONTRIBUTOR = new ModActionType("REMOVE_CONTRIBUTOR", 59, "REMOVE_CONTRIBUTOR");
    public static final ModActionType REMOVE_LINK = new ModActionType("REMOVE_LINK", 60, "REMOVE_LINK");
    public static final ModActionType REMOVE_MODERATOR = new ModActionType("REMOVE_MODERATOR", 61, "REMOVE_MODERATOR");
    public static final ModActionType REMOVE_WIKI_CONTRIBUTOR = new ModActionType("REMOVE_WIKI_CONTRIBUTOR", 62, "REMOVE_WIKI_CONTRIBUTOR");
    public static final ModActionType REORDER_MODERATORS = new ModActionType("REORDER_MODERATORS", 63, "REORDER_MODERATORS");
    public static final ModActionType REORDER_REMOVAL_REASON = new ModActionType("REORDER_REMOVAL_REASON", 64, "REORDER_REMOVAL_REASON");
    public static final ModActionType REORDER_RULES = new ModActionType("REORDER_RULES", 65, "REORDER_RULES");
    public static final ModActionType REQUEST_ASSISTANCE = new ModActionType("REQUEST_ASSISTANCE", 66, "REQUEST_ASSISTANCE");
    public static final ModActionType SET_CONTEST_MODE = new ModActionType("SET_CONTEST_MODE", 67, "SET_CONTEST_MODE");
    public static final ModActionType SET_PERMISSIONS = new ModActionType("SET_PERMISSIONS", 68, "SET_PERMISSIONS");
    public static final ModActionType SET_SUGGESTEDSORT = new ModActionType("SET_SUGGESTEDSORT", 69, "SET_SUGGESTEDSORT");
    public static final ModActionType SHOW_COMMENT = new ModActionType("SHOW_COMMENT", 70, "SHOW_COMMENT");
    public static final ModActionType SNOOZE_REPORTS = new ModActionType("SNOOZE_REPORTS", 71, "SNOOZE_REPORTS");
    public static final ModActionType SPAM_COMMENT = new ModActionType("SPAM_COMMENT", 72, "SPAM_COMMENT");
    public static final ModActionType SPAM_LINK = new ModActionType("SPAM_LINK", 73, "SPAM_LINK");
    public static final ModActionType SPOILER = new ModActionType("SPOILER", 74, "SPOILER");
    public static final ModActionType STICKY = new ModActionType("STICKY", 75, "STICKY");
    public static final ModActionType SUBMIT_CONTENT_RATING_SURVEY = new ModActionType("SUBMIT_CONTENT_RATING_SURVEY", 76, "SUBMIT_CONTENT_RATING_SURVEY");
    public static final ModActionType SUBMIT_SCHEDULED_POST = new ModActionType("SUBMIT_SCHEDULED_POST", 77, "SUBMIT_SCHEDULED_POST");
    public static final ModActionType UNBAN_USER = new ModActionType("UNBAN_USER", 78, "UNBAN_USER");
    public static final ModActionType UNIGNORE_REPORTS = new ModActionType("UNIGNORE_REPORTS", 79, "UNIGNORE_REPORTS");
    public static final ModActionType UNINVITE_MODERATOR = new ModActionType("UNINVITE_MODERATOR", 80, "UNINVITE_MODERATOR");
    public static final ModActionType UNLOCK = new ModActionType("UNLOCK", 81, "UNLOCK");
    public static final ModActionType UNMUTE_USER = new ModActionType("UNMUTE_USER", 82, "UNMUTE_USER");
    public static final ModActionType UNSET_CONTEST_MODE = new ModActionType("UNSET_CONTEST_MODE", 83, "UNSET_CONTEST_MODE");
    public static final ModActionType UNSNOOZE_REPORTS = new ModActionType("UNSNOOZE_REPORTS", 84, "UNSNOOZE_REPORTS");
    public static final ModActionType UNSPOILER = new ModActionType("UNSPOILER", 85, "UNSPOILER");
    public static final ModActionType UNSTICKY = new ModActionType("UNSTICKY", 86, "UNSTICKY");
    public static final ModActionType UPDATE_REMOVAL_REASON = new ModActionType("UPDATE_REMOVAL_REASON", 87, "UPDATE_REMOVAL_REASON");
    public static final ModActionType WIKI_BANNED = new ModActionType("WIKI_BANNED", 88, "WIKI_BANNED");
    public static final ModActionType WIKI_CONTRIBUTOR = new ModActionType("WIKI_CONTRIBUTOR", 89, "WIKI_CONTRIBUTOR");
    public static final ModActionType WIKI_PAGE_LISTED = new ModActionType("WIKI_PAGE_LISTED", 90, "WIKI_PAGE_LISTED");
    public static final ModActionType WIKI_PERM_LEVEL = new ModActionType("WIKI_PERM_LEVEL", 91, "WIKI_PERM_LEVEL");
    public static final ModActionType WIKI_REVISE = new ModActionType("WIKI_REVISE", 92, "WIKI_REVISE");
    public static final ModActionType WIKI_UNBANNED = new ModActionType("WIKI_UNBANNED", 93, "WIKI_UNBANNED");
    public static final ModActionType CHAT_APPROVE_MESSAGE = new ModActionType("CHAT_APPROVE_MESSAGE", 94, "CHAT_APPROVE_MESSAGE");
    public static final ModActionType CHAT_REMOVE_MESSAGE = new ModActionType("CHAT_REMOVE_MESSAGE", 95, "CHAT_REMOVE_MESSAGE");
    public static final ModActionType CHAT_BAN_USER = new ModActionType("CHAT_BAN_USER", 96, "CHAT_BAN_USER");
    public static final ModActionType CHAT_UNBAN_USER = new ModActionType("CHAT_UNBAN_USER", 97, "CHAT_UNBAN_USER");
    public static final ModActionType CHAT_INVITE_HOST = new ModActionType("CHAT_INVITE_HOST", 98, "CHAT_INVITE_HOST");
    public static final ModActionType CHAT_REMOVE_HOST = new ModActionType("CHAT_REMOVE_HOST", 99, "CHAT_REMOVE_HOST");
    public static final ModActionType MOD_RECRUITMENT_ENABLE = new ModActionType("MOD_RECRUITMENT_ENABLE", 100, "MOD_RECRUITMENT_ENABLE");
    public static final ModActionType MOD_RECRUITMENT_DISABLE = new ModActionType("MOD_RECRUITMENT_DISABLE", 101, "MOD_RECRUITMENT_DISABLE");
    public static final ModActionType MOD_RECRUITMENT_UPDATE_TEMPLATE = new ModActionType("MOD_RECRUITMENT_UPDATE_TEMPLATE", 102, "MOD_RECRUITMENT_UPDATE_TEMPLATE");
    public static final ModActionType MOD_RECRUITMENT_APPLICATION_RESPOND = new ModActionType("MOD_RECRUITMENT_APPLICATION_RESPOND", 103, "MOD_RECRUITMENT_APPLICATION_RESPOND");
    public static final ModActionType MOD_RECRUITMENT_APPLICATION_REMOVE = new ModActionType("MOD_RECRUITMENT_APPLICATION_REMOVE", 104, "MOD_RECRUITMENT_APPLICATION_REMOVE");
    public static final ModActionType UNKNOWN__ = new ModActionType("UNKNOWN__", 105, "UNKNOWN__");

    private static final /* synthetic */ ModActionType[] $values() {
        return new ModActionType[]{ACCEPT_MODERATOR_INVITE, ADD_COMMUNITY_TOPICS, ADD_CONTRIBUTOR, ADD_ENFORCEMENT_ACTION_FEEDBACK, ADD_MODERATOR, ADD_NOTE, ADD_REMOVAL_REASON, ADJUST_POST_CROWD_CONTROL_LEVEL, ENABLE_POST_CROWD_CONTROL_FILTER, DISABLE_POST_CROWD_CONTROL_FILTER, APPROVE_AWARD, APPROVE_COMMENT, APPROVE_LINK, BAN_USER, CREATE_AWARD, CREATE_SCHEDULED_POST, CREATE_REMOVAL_REASON, COLLECTIONS, COMMUNITY_STATUS, COMMUNITY_STYLING, COMMUNITY_WELCOME_PAGE, COMMUNITY_WIDGETS, CREATE_RULE, DELETE_AWARD, DELETE_RULE, DELETE_SCHEDULED_POST, DEV_PLATFORM_APP_CHANGED, DEV_PLATFORM_APP_DISABLED, DEV_PLATFORM_APP_ENABLED, DEV_PLATFORM_APP_INSTALLED, DEV_PLATFORM_APP_UNINSTALLED, DELETE_OVERRIDDEN_CLASSIFICATION, DELETE_NOTE, DELETE_REMOVAL_REASON, DISABLE_AWARD, DISTINGUISH, EDIT_COMMENT_REQUIREMENTS, EDIT_ENFORCEMENT_ACTION, EDIT_FLAIR, EDIT_POST_REQUIREMENTS, EDIT_RULE, EDIT_SAVED_RESPONSE, EDIT_SCHEDULED_POST, EDIT_SETTINGS, ENABLE_AWARD, EVENTS, HIDDEN_AWARD, IGNORE_REPORTS, INVITE_MODERATOR, INVITE_SUBSCRIBER, LOCK, MARK_NSFW, MARK_ORIGINAL_CONTENT, MOD_AWARD_GIVEN, MODMAIL_ENROLLMENT, MUTE_USER, OVERRIDE_CLASSIFICATION, REMOVE_COMMENT, REMOVE_COMMUNITY_TOPICS, REMOVE_CONTRIBUTOR, REMOVE_LINK, REMOVE_MODERATOR, REMOVE_WIKI_CONTRIBUTOR, REORDER_MODERATORS, REORDER_REMOVAL_REASON, REORDER_RULES, REQUEST_ASSISTANCE, SET_CONTEST_MODE, SET_PERMISSIONS, SET_SUGGESTEDSORT, SHOW_COMMENT, SNOOZE_REPORTS, SPAM_COMMENT, SPAM_LINK, SPOILER, STICKY, SUBMIT_CONTENT_RATING_SURVEY, SUBMIT_SCHEDULED_POST, UNBAN_USER, UNIGNORE_REPORTS, UNINVITE_MODERATOR, UNLOCK, UNMUTE_USER, UNSET_CONTEST_MODE, UNSNOOZE_REPORTS, UNSPOILER, UNSTICKY, UPDATE_REMOVAL_REASON, WIKI_BANNED, WIKI_CONTRIBUTOR, WIKI_PAGE_LISTED, WIKI_PERM_LEVEL, WIKI_REVISE, WIKI_UNBANNED, CHAT_APPROVE_MESSAGE, CHAT_REMOVE_MESSAGE, CHAT_BAN_USER, CHAT_UNBAN_USER, CHAT_INVITE_HOST, CHAT_REMOVE_HOST, MOD_RECRUITMENT_ENABLE, MOD_RECRUITMENT_DISABLE, MOD_RECRUITMENT_UPDATE_TEMPLATE, MOD_RECRUITMENT_APPLICATION_RESPOND, MOD_RECRUITMENT_APPLICATION_REMOVE, UNKNOWN__};
    }

    /* JADX WARN: Type inference failed for: r0v108, types: [java.lang.Object, fg3.ux] */
    static {
        ModActionType[] $values = $values();
        $VALUES = $values;
        $ENTRIES = kotlin.enums.a.a($values);
        Companion = new Object();
        type = new e0("ModActionType", c0.l("ACCEPT_MODERATOR_INVITE", "ADD_COMMUNITY_TOPICS", "ADD_CONTRIBUTOR", "ADD_ENFORCEMENT_ACTION_FEEDBACK", "ADD_MODERATOR", "ADD_NOTE", "ADD_REMOVAL_REASON", "ADJUST_POST_CROWD_CONTROL_LEVEL", "ENABLE_POST_CROWD_CONTROL_FILTER", "DISABLE_POST_CROWD_CONTROL_FILTER", "APPROVE_AWARD", "APPROVE_COMMENT", "APPROVE_LINK", "BAN_USER", "CREATE_AWARD", "CREATE_SCHEDULED_POST", "CREATE_REMOVAL_REASON", "COLLECTIONS", "COMMUNITY_STATUS", "COMMUNITY_STYLING", "COMMUNITY_WELCOME_PAGE", "COMMUNITY_WIDGETS", "CREATE_RULE", "DELETE_AWARD", "DELETE_RULE", "DELETE_SCHEDULED_POST", "DEV_PLATFORM_APP_CHANGED", "DEV_PLATFORM_APP_DISABLED", "DEV_PLATFORM_APP_ENABLED", "DEV_PLATFORM_APP_INSTALLED", "DEV_PLATFORM_APP_UNINSTALLED", "DELETE_OVERRIDDEN_CLASSIFICATION", "DELETE_NOTE", "DELETE_REMOVAL_REASON", "DISABLE_AWARD", "DISTINGUISH", "EDIT_COMMENT_REQUIREMENTS", "EDIT_ENFORCEMENT_ACTION", "EDIT_FLAIR", "EDIT_POST_REQUIREMENTS", "EDIT_RULE", "EDIT_SAVED_RESPONSE", "EDIT_SCHEDULED_POST", "EDIT_SETTINGS", "ENABLE_AWARD", "EVENTS", "HIDDEN_AWARD", "IGNORE_REPORTS", "INVITE_MODERATOR", "INVITE_SUBSCRIBER", "LOCK", "MARK_NSFW", "MARK_ORIGINAL_CONTENT", "MOD_AWARD_GIVEN", "MODMAIL_ENROLLMENT", "MUTE_USER", "OVERRIDE_CLASSIFICATION", "REMOVE_COMMENT", "REMOVE_COMMUNITY_TOPICS", "REMOVE_CONTRIBUTOR", "REMOVE_LINK", "REMOVE_MODERATOR", "REMOVE_WIKI_CONTRIBUTOR", "REORDER_MODERATORS", "REORDER_REMOVAL_REASON", "REORDER_RULES", "REQUEST_ASSISTANCE", "SET_CONTEST_MODE", "SET_PERMISSIONS", "SET_SUGGESTEDSORT", "SHOW_COMMENT", "SNOOZE_REPORTS", "SPAM_COMMENT", "SPAM_LINK", "SPOILER", "STICKY", "SUBMIT_CONTENT_RATING_SURVEY", "SUBMIT_SCHEDULED_POST", "UNBAN_USER", "UNIGNORE_REPORTS", "UNINVITE_MODERATOR", "UNLOCK", "UNMUTE_USER", "UNSET_CONTEST_MODE", "UNSNOOZE_REPORTS", "UNSPOILER", "UNSTICKY", "UPDATE_REMOVAL_REASON", "WIKI_BANNED", "WIKI_CONTRIBUTOR", "WIKI_PAGE_LISTED", "WIKI_PERM_LEVEL", "WIKI_REVISE", "WIKI_UNBANNED", "CHAT_APPROVE_MESSAGE", "CHAT_REMOVE_MESSAGE", "CHAT_BAN_USER", "CHAT_UNBAN_USER", "CHAT_INVITE_HOST", "CHAT_REMOVE_HOST", "MOD_RECRUITMENT_ENABLE", "MOD_RECRUITMENT_DISABLE", "MOD_RECRUITMENT_UPDATE_TEMPLATE", "MOD_RECRUITMENT_APPLICATION_RESPOND", "MOD_RECRUITMENT_APPLICATION_REMOVE"));
    }

    private ModActionType(String str, int i, String str2) {
        this.rawValue = str2;
    }

    @NotNull
    public static a getEntries() {
        return $ENTRIES;
    }

    public static ModActionType valueOf(String str) {
        return (ModActionType) Enum.valueOf(ModActionType.class, str);
    }

    public static ModActionType[] values() {
        return (ModActionType[]) $VALUES.clone();
    }

    @NotNull
    public final String getRawValue() {
        return this.rawValue;
    }
}
